// Issue-related tools
export {
  ISSUE_LIST_TOOL,
  ISSUE_GET_TOOL,
  ISSUE_CREATE_TOOL,
  ISSUE_UPDATE_TOOL,
  ISSUE_DELETE_TOOL,
  ISSUE_ADD_WATCHER_TOOL,
  ISSUE_REMOVE_WATCHER_TOOL,
} from "./issues.js";

// Project-related tools
export {
  PROJECT_LIST_TOOL,
  PROJECT_SHOW_TOOL,
  PROJECT_CREATE_TOOL,
  PROJECT_UPDATE_TOOL,
  PROJECT_ARCHIVE_TOOL,
  PROJECT_UNARCHIVE_TOOL,
  PROJECT_DELETE_TOOL,
  PROJECT_LIST_STATUSES_TOOL, // Added new tool
} from "./projects.js";

// Time entry tools
export {
  TIME_ENTRY_LIST_TOOL,
  TIME_ENTRY_SHOW_TOOL,
  TIME_ENTRY_CREATE_FOR_PROJECT_TOOL,
  TIME_ENTRY_CREATE_FOR_ISSUE_TOOL,
  TIME_ENTRY_UPDATE_TOOL,
  TIME_ENTRY_DELETE_TOOL,
} from "./time_entries.js";

// User-related tools
export {
  USER_LIST_TOOL,
  USER_SHOW_TOOL,
  USER_CREATE_TOOL,
  USER_UPDATE_TOOL,
  USER_DELETE_TOOL,
} from "./users.js";

// Wiki-related tools
export {
  WIKI_LIST_PAGES_TOOL,
  WIKI_GET_PAGE_TOOL,
  WIKI_LIST_HISTORY_TOOL,
  WIKI_LIST_ATTACHMENTS_TOOL,
  WIKI_CREATE_OR_UPDATE_PAGE_TOOL,
} from "./wiki.js";
